version: "3"
services:
  django:
    container_name: "django"
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - "./testproject:/opt/testproject"
    ports:
      - "8000:8000"
    # 0.0.0.0:8000 を書かないと docker の外からアクセスできない
    command: ["bash", "-c", "./manage.py runserver 0.0.0.0:8000"]
    # command: ["bash", "-c", "gunicorn -w 1 -b 0.0.0.0:8000 testproject.wsgi:application"]
