version: "3"
services:
  django:
    container_name: "django"
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - "./testproject:/opt/testproject"
      - "./nginx.conf:/etc/nginx/sites-enabled/django.conf"
    ports:
      - "8000:8000"
      - "58080:58080"
    # 0.0.0.0:8000 を書かないと docker の外からアクセスできない
    command: ["bash", "-c", "service nginx start && gunicorn testproject.wsgi --bind=unix:/var/run/gunicorn.sock"]
